In [1]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [3]:
import numpy as np
np.random.rand(4)

array([0.97805214, 0.64992111, 0.2909868 , 0.57192641])

In [9]:
a4 = np.arange(1,4,1)
a4.ndim

1

In [5]:
np.random.rand(4, 1)

array([[0.1290736 ],
       [0.96960132],
       [0.08032357],
       [0.45226945]])

In [10]:
a5 = np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [11]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [16]:
r=np.reshape(np.arange(0,36),(6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [17]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [18]:
r[2:3,2:3]

array([[14]])

In [19]:
r[[2,3],[2,3]]

array([14, 21])

In [21]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5